version:                "3"
services:
  qol_stan:
      image: kosugitti/rstan-env:latest
      volumes:
        - ./:/home/rstudio
      ports:
        - 8787:8787
      environment:
        - PASSWORD=Lunar
